# Text Learning via ML

1. Bag Of Words
2. StopWords
3. Stemming
4. NLTK
5. TF-IDF

# Bag of Words

Bag of Words is like tossing all the words we encounter as individual tokens with their frequency of occurance in input. If the word happens to repeat we will have only one instance of it with tied frequency on how many times it has been repeated.

** Note: Loves and Love are not same, advance tooling to be studied later will help cover such issues **
![ML](images/ml62.png)

** Note: 'Chicago Bulls' is sports team, but at this stage system can't contextually understand this, will treat this as separate words, advance tooling to be studied later will help cover such issues **

![ML](images/ml61.png)


## Let's implement BagOfWords with sklearn

** In sklearn Bag Of Words is referred as CountVectorizer as it doing nothing counting word frequencies **

http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction


In [5]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

corpus = [
     'This is the first document.',
     'This is the second second document.',
     'And the third one.',
     'Is this the first document?']

# Fit words from corpus, which means convert them to indices
bag_of_words = vectorizer.fit(corpus)

# Transform count the words frequency, keep one instance with with count
bag_of_words = vectorizer.transform(corpus)

## *** Alternative above two steps can be done in one as : vectorizer.fit_transform(corpus)

<4x9 sparse matrix of type '<type 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [15]:
print "Example: (0,1) stands for 0th document (first document) & 1st word, ..."
print " which is nothing by ''this'', followed by occurence count in that document ..."
print("")
print bag_of_words

Example: (0,1) stands for 0th document (first document) & 1st word, ...
 which is nothing by ''this'', followed by occurence count in that document ...

  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 6)	1
  (0, 8)	1
  (1, 1)	1
  (1, 3)	1
  (1, 5)	2
  (1, 6)	1
  (1, 8)	1
  (2, 0)	1
  (2, 4)	1
  (2, 6)	1
  (2, 7)	1
  (3, 1)	1
  (3, 2)	1
  (3, 3)	1
  (3, 6)	1
  (3, 8)	1


In [8]:
vectorizer.get_feature_names()

[u'and',
 u'document',
 u'first',
 u'is',
 u'one',
 u'second',
 u'the',
 u'third',
 u'this']

In [7]:
vectorizer.vocabulary_

{u'and': 0,
 u'document': 1,
 u'first': 2,
 u'is': 3,
 u'one': 4,
 u'second': 5,
 u'the': 6,
 u'third': 7,
 u'this': 8}

In [33]:
print "WE HAVE FEATURE LIST OR VOCABULARY OF 9 WORDS AS LISTED ABOVE ..."
print "IT IS SORTED IN ALPHABETICAL ORDER ..."
print "THE ARRAY VALUES BELOW SHOWS 0 OR 1 IF WORD FOUND IN DOCUMENT AT VOCAB INDEX ..."
print "HENCE THE ARRAY LEGTH AS 9 ...\n"

print 'This is the first document.'
print  bag_of_words.toarray()[0]

print("")

print 'This is the second second document.'
print  bag_of_words.toarray()[1]
print("")

print 'And the third one.'
print  bag_of_words.toarray()[2]
print("")

print 'Is this the first document?'
print  bag_of_words.toarray()[3]
print("")

print  bag_of_words.toarray()
print("")

WE HAVE FEATURE LIST OR VOCABULARY OF 9 WORDS AS LISTED ABOVE ...
IT IS SORTED IN ALPHABETICAL ORDER ...
THE ARRAY VALUES BELOW SHOWS 0 OR 1 IF WORD FOUND IN DOCUMENT AT VOCAB INDEX ...
HENCE THE ARRAY LEGTH AS 9 ...

This is the first document.
[0 1 1 1 0 0 1 0 1]

This is the second second document.
[0 1 0 1 0 2 1 0 1]

And the third one.
[1 0 0 0 1 0 1 1 0]

Is this the first document?
[0 1 1 1 0 0 1 0 1]

[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]



In [9]:
vectorizer.vocabulary_.get("third")

7